In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.datasets import fetch_20newsgroups
from sklearn.decomposition import NMF, LatentDirichletAllocation

def display_topics(model, feature_names, no_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print( "Topic %d:" % (topic_idx))
        print (" ".join([feature_names[i]
                        for i in topic.argsort()[:-no_top_words - 1:-1]]))

dataset = fetch_20newsgroups(shuffle=True, random_state=1, remove=('headers', 'footers', 'quotes'))
documents = dataset.data

no_features = 1000

# NMF is able to use tf-idf
tfidf_vectorizer = TfidfVectorizer(max_df=0.95, min_df=2, max_features=no_features, stop_words='english')
tfidf = tfidf_vectorizer.fit_transform(documents)
tfidf_feature_names = tfidf_vectorizer.get_feature_names()
vocab=tfidf_vectorizer.vocabulary_

In [11]:
type(vocab)

dict

In [12]:
vocab

{'sure': 872,
 'story': 860,
 'did': 303,
 'statement': 854,
 'media': 589,
 'pro': 714,
 'israeli': 497,
 'world': 985,
 'having': 444,
 'letter': 535,
 'try': 914,
 'think': 897,
 'reason': 745,
 'report': 760,
 'clearly': 229,
 'reports': 762,
 'received': 748,
 'government': 424,
 'makes': 573,
 'away': 146,
 'look': 554,
 'jews': 502,
 'got': 422,
 'power': 703,
 'expect': 359,
 'people': 670,
 'read': 741,
 'faq': 369,
 'actually': 88,
 'accept': 83,
 'hard': 441,
 'atheism': 138,
 'need': 620,
 'little': 546,
 'faith': 366,
 'runs': 781,
 'jim': 503,
 'sorry': 837,
 'oh': 644,
 'just': 508,
 'end': 341,
 'maybe': 584,
 'start': 851,
 'new': 625,
 'newsgroup': 627,
 'alt': 103,
 'won': 978,
 'big': 162,
 'don': 321,
 'points': 691,
 'like': 540,
 'know': 516,
 'ask': 134,
 'question': 734,
 'sort': 838,
 'want': 954,
 'continue': 258,
 'israel': 496,
 'stop': 859,
 'asking': 136,
 'questions': 735,
 'work': 981,
 'bad': 149,
 'attack': 139,
 'group': 429,
 'center': 203,
 'policy

In [13]:
type(tfidf)

scipy.sparse.csr.csr_matrix

In [14]:
vocab.keys

<function dict.keys>

In [15]:
vocab.keys()

dict_keys(['sure', 'story', 'did', 'statement', 'media', 'pro', 'israeli', 'world', 'having', 'letter', 'try', 'think', 'reason', 'report', 'clearly', 'reports', 'received', 'government', 'makes', 'away', 'look', 'jews', 'got', 'power', 'expect', 'people', 'read', 'faq', 'actually', 'accept', 'hard', 'atheism', 'need', 'little', 'faith', 'runs', 'jim', 'sorry', 'oh', 'just', 'end', 'maybe', 'start', 'new', 'newsgroup', 'alt', 'won', 'big', 'don', 'points', 'like', 'know', 'ask', 'question', 'sort', 'want', 'continue', 'israel', 'stop', 'asking', 'questions', 'work', 'bad', 'attack', 'group', 'center', 'policy', 'research', 'change', 'product', 'area', 'clipper', 'came', 'key', 'yes', 'technology', 'drive', 'cost', 'use', 'present', 'man', 'street', 'going', 'especially', 'guy', 'probably', 'doesn', 'real', 'gov', 'year', 'air', 'voice', 'privacy', 'phone', 'line', 'close', 'pc', 'unfortunately', 'time', 'right', 'certainly', 'post', 'rules', 'does', 'matter', 'll', 'good', 'let', 'mail

In [19]:
np.count(vocab.keys())

NameError: name 'np' is not defined

In [25]:
j

2000

In [24]:
for i in vocab.keys():
    j+=1

In [30]:
tfidf[1][10]

IndexError: row index (10) out of range

In [27]:
vocab.values()

dict_values([872, 860, 303, 854, 589, 714, 497, 985, 444, 535, 914, 897, 745, 760, 229, 762, 748, 424, 573, 146, 554, 502, 422, 703, 359, 670, 741, 369, 88, 83, 441, 138, 620, 546, 366, 781, 503, 837, 644, 508, 341, 584, 851, 625, 627, 103, 978, 162, 321, 691, 540, 516, 134, 734, 838, 954, 258, 496, 859, 136, 735, 981, 149, 139, 429, 203, 693, 767, 207, 719, 124, 231, 191, 509, 997, 886, 325, 263, 931, 705, 575, 861, 420, 349, 434, 715, 319, 743, 423, 995, 98, 949, 712, 676, 543, 232, 668, 924, 900, 773, 205, 700, 778, 318, 582, 550, 421, 534, 569, 336, 529, 646, 959, 288, 500, 113, 284, 632, 645, 751, 831, 722, 65, 560, 56, 144, 28, 34, 306, 426, 822, 194, 158, 792, 195, 641, 173, 717, 247, 210, 189, 672, 637, 380, 612, 46, 840, 586, 669, 718, 790, 890, 19, 608, 518, 889, 791, 747, 572, 188, 102, 391, 390, 531, 475, 961, 987, 539, 338, 758, 907, 514, 592, 631, 658, 8, 996, 538, 320, 533, 932, 193, 9, 29, 557, 334, 710, 887, 893, 123, 425, 545, 24, 5, 18, 249, 702, 122, 478, 143, 826, 

In [31]:
print(tfidf)

  (0, 703)	0.12649800094895408
  (0, 422)	0.11440503782900698
  (0, 502)	0.16143119574434353
  (0, 554)	0.11764823931486343
  (0, 146)	0.1321150797895706
  (0, 573)	0.13397806229297743
  (0, 424)	0.1286860210682992
  (0, 748)	0.16159319274170325
  (0, 762)	0.16593512050235812
  (0, 229)	0.16031961808699013
  (0, 760)	0.16377738132726433
  (0, 745)	0.13017163327559614
  (0, 897)	0.08921604715652667
  (0, 914)	0.1211198624990018
  (0, 535)	0.170527849290146
  (0, 444)	0.12553649604441633
  (0, 985)	0.1234486147818597
  (0, 497)	0.3492941756834514
  (0, 714)	0.16687897474873634
  (0, 589)	0.6706185322723434
  (0, 854)	0.1548789339575849
  (0, 303)	0.10688890801049414
  (0, 860)	0.15939664046839722
  (0, 872)	0.11320169009663988
  (1, 321)	0.08508020140594663
  :	:
  (11313, 758)	0.12570119483680048
  (11313, 747)	0.14997932614513387
  (11313, 840)	0.14657229469463148
  (11313, 637)	0.141706720017083
  (11313, 210)	0.1348772638908091
  (11313, 560)	0.11495605591940465
  (11313, 646)	0.2342

In [32]:
str(n_topics)

NameError: name 'n_topics' is not defined

In [35]:
str(300)

'300'

In [36]:
len(tfidf)

TypeError: sparse matrix length is ambiguous; use getnnz() or shape[0]

In [39]:
k

0

In [40]:
for i in range(len(tfidf)):
    k+=1

TypeError: sparse matrix length is ambiguous; use getnnz() or shape[0]

In [59]:
a=([1,2,3,5,6,8],[6,8,9,6,5,3])

In [44]:
a

([1, 2.3, 5, 6, 8], [6, 8, 9, 6, 5, 3])

In [45]:
tomatrix(a)

NameError: name 'tomatrix' is not defined

In [60]:
b=np.mat(a)

In [49]:
import numpy as np

In [61]:
b

matrix([[1, 2, 3, 5, 6, 8],
        [6, 8, 9, 6, 5, 3]])

In [62]:
print(b)

[[1 2 3 5 6 8]
 [6 8 9 6 5 3]]


In [63]:
len(b)

2